buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // AGP sürümünü güncelledik (Gradle 8+ ve 9+ uyumlu)
        classpath 'com.android.tools.build:gradle:8.1.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
